name: abroad
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  get:
  google_fonts: ^4.0.3
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.7
  rxdart: ^0.27.2
  google_places_flutter: ^2.0.5
  google_maps_flutter_web: ^0.4.0+7
  get_it: ^7.2.0
  flutter_native_splash: ^2.2.19
  line_awesome_flutter: ^2.0.0
  page_transition: ^2.0.9
  flutter_launcher_icons: ^0.12.0
  flutter_keyboard_visibility: ^5.4.1
  avoid_keyboard: ^0.3.0
  flutter_bloc: ^8.0.0
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  flutter_staggered_grid_view: ^0.4.1
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.1.0
  lottie: ^2.3.2
  flutter_screenutil: ^5.7.0
  intl: ^0.17.0
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"


  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#7546F4"
  image: assets/images/logo_with_name.png

flutter:
  assets:
    - assets/images/
    - assets/images/welcome_images/
    - assets/images/signin_images/
    - assets/images/signup_images/
    - assets/images/profile_images/

  uses-material-design: true

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true